#!/bin/bash


python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p1.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p2.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p3.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p4.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p5.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p6.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p7.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p8.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p9.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p10.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p11.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p12.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p13.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p14.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p15.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p16.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p17.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p18.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p19.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p20.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p21.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p22.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p23.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p24.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p25.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p26.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p27.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p28.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p29.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p30.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p31.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p32.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p33.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p34.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p35.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p36.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p37.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p38.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p39.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p40.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p41.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p42.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p43.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p44.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p45.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p46.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p47.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p48.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p49.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p50.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p51.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p52.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p53.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p54.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p55.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p56.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p57.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p58.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p59.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p60.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p61.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p62.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p63.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p64.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p65.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p66.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p67.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p68.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p69.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p70.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p71.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p72.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p73.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p74.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p75.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p76.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p77.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p78.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p79.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p80.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p81.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p82.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p83.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p84.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p85.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p86.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p87.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p88.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p89.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p90.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p91.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p92.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p93.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p94.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p95.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p96.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p97.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p98.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p99.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p100.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p101.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p102.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p103.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p104.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p105.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p106.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p107.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p108.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p109.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p110.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p111.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p112.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p113.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p114.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p115.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p116.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p117.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p118.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p119.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p120.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p121.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p122.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p123.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p124.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p125.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p126.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p127.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p128.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p129.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p130.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p131.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p132.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p133.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p134.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p135.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p136.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p137.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p138.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p139.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p140.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p141.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p142.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p143.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p144.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p145.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p146.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p147.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p148.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p149.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p150.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p151.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p152.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p153.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p154.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p155.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p156.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p157.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p158.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p159.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p160.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p161.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p162.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p163.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p164.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p165.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p166.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p167.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p168.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p169.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p170.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p171.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p172.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p173.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p174.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p175.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p176.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p177.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p178.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p179.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p180.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p181.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p182.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p183.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p184.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p185.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p186.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p187.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p188.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p189.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p190.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p191.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p192.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p193.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p194.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p195.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p196.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p197.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p198.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p199.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p200.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p201.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p202.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p203.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p204.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p205.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p206.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p207.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p208.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p209.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p210.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p211.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p212.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p213.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p214.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p215.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p216.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p217.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p218.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p219.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p220.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p221.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p222.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p223.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p224.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p225.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p226.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p227.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p228.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p229.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p230.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p231.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p232.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p233.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p234.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p235.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p236.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p237.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p238.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p239.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p240.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p241.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p242.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p243.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p244.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p245.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p246.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p247.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p248.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p249.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p250.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p251.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p252.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p253.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p254.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p255.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p256.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p257.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p258.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p259.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p260.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p261.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p262.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p263.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p264.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p265.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p266.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p267.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p268.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p269.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p270.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p271.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p272.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p273.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p274.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p275.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p276.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p277.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p278.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p279.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p280.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p281.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p282.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p283.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p284.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p285.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p286.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p287.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p288.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p289.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p290.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p291.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p292.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p293.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p294.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p295.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p296.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p297.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p298.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p299.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p300.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p301.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p302.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p303.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p304.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p305.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p306.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p307.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p308.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p309.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p310.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p311.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p312.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p313.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p314.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p315.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p316.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p317.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p318.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p319.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p320.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p321.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p322.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p323.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p324.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p325.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p326.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p327.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p328.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p329.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p330.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p331.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p332.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p333.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p334.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p335.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p336.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p337.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p338.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p339.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p340.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p341.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p342.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p343.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p344.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p345.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p346.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p347.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p348.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p349.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p350.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p351.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p352.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p353.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p354.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p355.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p356.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p357.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p358.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p359.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p360.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p361.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p362.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p363.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p364.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p365.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p366.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p367.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p368.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p369.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p370.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p371.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p372.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p373.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p374.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p375.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p376.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p377.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p378.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p379.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p380.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p381.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p382.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p383.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p384.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p385.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p386.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p387.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p388.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p389.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p390.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p391.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p392.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p393.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p394.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p395.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p396.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p397.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p398.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p399.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p400.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p401.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p402.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p403.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p404.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p405.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p406.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p407.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p408.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p409.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p410.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p411.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p412.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p413.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p414.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p415.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p416.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p417.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p418.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p419.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p420.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p421.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p422.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p423.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p424.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p425.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p426.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p427.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p428.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p429.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p430.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p431.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p432.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p433.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p434.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p435.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p436.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p437.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p438.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p439.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p440.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p441.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p442.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p443.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p444.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_mat/split1/pbsim/p445.ccs_report.txt

python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p1.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p2.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p3.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p4.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p5.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p6.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p7.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p8.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p9.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p10.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p11.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p12.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p13.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p14.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p15.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p16.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p17.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p18.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p19.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p20.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p21.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p22.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p23.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p24.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p25.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p26.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p27.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p28.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p29.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p30.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p31.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p32.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p33.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p34.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p35.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p36.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p37.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p38.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p39.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p40.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p41.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p42.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p43.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p44.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p45.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p46.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p47.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p48.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p49.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p50.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p51.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p52.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p53.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p54.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p55.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p56.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p57.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p58.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p59.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p60.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p61.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p62.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p63.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p64.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p65.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p66.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p67.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p68.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p69.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p70.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p71.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p72.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p73.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p74.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p75.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p76.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p77.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p78.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p79.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p80.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p81.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p82.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p83.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p84.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p85.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p86.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p87.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p88.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p89.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p90.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p91.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p92.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p93.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p94.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p95.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p96.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p97.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p98.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p99.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p100.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p101.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p102.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p103.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p104.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p105.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p106.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p107.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p108.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p109.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p110.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p111.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p112.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p113.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p114.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p115.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p116.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p117.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p118.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p119.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p120.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p121.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p122.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p123.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p124.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p125.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p126.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p127.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p128.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p129.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p130.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p131.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p132.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p133.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p134.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p135.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p136.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p137.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p138.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p139.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p140.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p141.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p142.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p143.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p144.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p145.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p146.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p147.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p148.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p149.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p150.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p151.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p152.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p153.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p154.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p155.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p156.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p157.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p158.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p159.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p160.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p161.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p162.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p163.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p164.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p165.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p166.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p167.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p168.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p169.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p170.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p171.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p172.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p173.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p174.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p175.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p176.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p177.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p178.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p179.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p180.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p181.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p182.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p183.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p184.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p185.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p186.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p187.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p188.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p189.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p190.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p191.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p192.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p193.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p194.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p195.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p196.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p197.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p198.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p199.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p200.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p201.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p202.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p203.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p204.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p205.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p206.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p207.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p208.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p209.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p210.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p211.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p212.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p213.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p214.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p215.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p216.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p217.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p218.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p219.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p220.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p221.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p222.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p223.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p224.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p225.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p226.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p227.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p228.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p229.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p230.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p231.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p232.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p233.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p234.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p235.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p236.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p237.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p238.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p239.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p240.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p241.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p242.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p243.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p244.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p245.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p246.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p247.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p248.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p249.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p250.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p251.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p252.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p253.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p254.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p255.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p256.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p257.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p258.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p259.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p260.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p261.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p262.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p263.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p264.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p265.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p266.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p267.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p268.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p269.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p270.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p271.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p272.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p273.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p274.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p275.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p276.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p277.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p278.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p279.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p280.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p281.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p282.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p283.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p284.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p285.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p286.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p287.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p288.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p289.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p290.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p291.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p292.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p293.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p294.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p295.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p296.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p297.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p298.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p299.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p300.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p301.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p302.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p303.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p304.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p305.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p306.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p307.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p308.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p309.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p310.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p311.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p312.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p313.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p314.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p315.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p316.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p317.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p318.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p319.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p320.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p321.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p322.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p323.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p324.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p325.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p326.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p327.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p328.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p329.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p330.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p331.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p332.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p333.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p334.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p335.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p336.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p337.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p338.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p339.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p340.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p341.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p342.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p343.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p344.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p345.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p346.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p347.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p348.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p349.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p350.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p351.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p352.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p353.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p354.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p355.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p356.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p357.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p358.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p359.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p360.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p361.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p362.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p363.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p364.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p365.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p366.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p367.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p368.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p369.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p370.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p371.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p372.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p373.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p374.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p375.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p376.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p377.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p378.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p379.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p380.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p381.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p382.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p383.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p384.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p385.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p386.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p387.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p388.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p389.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p390.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p391.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p392.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p393.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p394.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p395.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p396.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p397.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p398.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p399.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p400.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p401.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p402.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p403.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p404.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p405.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p406.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p407.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p408.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p409.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p410.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p411.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p412.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p413.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p414.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p415.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p416.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p417.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p418.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p419.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p420.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p421.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p422.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p423.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p424.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p425.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p426.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p427.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p428.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p429.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p430.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p431.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p432.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p433.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p434.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p435.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p436.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p437.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p438.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p439.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p440.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p441.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p442.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p443.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p444.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p445.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p446.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p447.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p448.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p449.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p450.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p451.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p452.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p453.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p454.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p455.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p456.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p457.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p458.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p459.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p460.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p461.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p462.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p463.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p464.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p465.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p466.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p467.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p468.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p469.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p470.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p471.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p472.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p473.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p474.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p475.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p476.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p477.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p478.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p479.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p480.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p481.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p482.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p483.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p484.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p485.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p486.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p487.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p488.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p489.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p490.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p491.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p492.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p493.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p494.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p495.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p496.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p497.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p498.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p499.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p500.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p501.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p502.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p503.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p504.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p505.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p506.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p507.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p508.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p509.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p510.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p511.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p512.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p513.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p514.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p515.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p516.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p517.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p518.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p519.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p520.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p521.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p522.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p523.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p524.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p525.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p526.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p527.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p528.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p529.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p530.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p531.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p532.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p533.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p534.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p535.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p536.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p537.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p538.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p539.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p540.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p541.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p542.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p543.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p544.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p545.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p546.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p547.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p548.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p549.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p550.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p551.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p552.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p553.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p554.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p555.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p556.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p557.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p558.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p559.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p560.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p561.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p562.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p563.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p564.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p565.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p566.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p567.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p568.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p569.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p570.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p571.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p572.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p573.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p574.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p575.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p576.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p577.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p578.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p579.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p580.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p581.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p582.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p583.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p584.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p585.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p586.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p587.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p588.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p589.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p590.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p591.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p592.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p593.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p594.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p595.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p596.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p597.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p598.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p599.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p600.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p601.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p602.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p603.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p604.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p605.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p606.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p607.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p608.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p609.ccs_report.txt
python3 /script/ccs_report_check.py /simulation/HG002_pat/split1/pbsim/p610.ccs_report.txt



